export const PUBLIC_ERROR_CODES = [
  // Validation
  'VALIDATION_FAILED',
  'MALFORMED_JSON',

  // Authentication and credentials
  'INVALID_CREDENTIALS',
  'CURRENT_PASSWORD_INVALID',
  'PASSWORDS_DO_NOT_MATCH',
  'NEW_PASSWORD_SAME_AS_CURRENT',

  // Registration and email verification
  'EMAIL_ALREADY_REGISTERED',
  'EMAIL_DOMAIN_NOT_ALLOWED',
  'EMAIL_NOT_VERIFIED',
  'EMAIL_VERIFICATION_TOKEN_INVALID',
  'EMAIL_VERIFICATION_TOKEN_EXPIRED',
  'EMAIL_ALREADY_VERIFIED',
  'VERIFICATION_EMAIL_COOLDOWN',
  'VERIFICATION_EMAIL_UNAVAILABLE',

  // Account and profile state
  'ACCOUNT_UNAVAILABLE',
  'ACCOUNT_STATE_CHANGED',
  'PROFILE_UNAVAILABLE',

  // Access and refresh tokens
  'ACCESS_TOKEN_REQUIRED',
  'ACCESS_TOKEN_INVALID',
  'ACCESS_TOKEN_EXPIRED',
  'REFRESH_TOKEN_REQUIRED',
  'REFRESH_TOKEN_INVALID',
  'REFRESH_TOKEN_EXPIRED',
  'REFRESH_TOKEN_REUSED',

  // Sessions
  'SESSION_UNAVAILABLE',
  'SESSION_NOT_FOUND',
  'SESSION_TOO_FRESH',
  'SESSION_LIMIT_REACHED',

  // Password recovery and change
  'PASSWORD_RESET_TOKEN_INVALID',
  'PASSWORD_CHANGED_CONCURRENTLY',

  // Rate limits
  'RATE_LIMIT_EXCEEDED',

  // Account deletion
  'ACCOUNT_DELETION_SCHEDULED',
  'ACCOUNT_DELETION_GRACE_PERIOD_EXPIRED',
  'ACCOUNT_DELETION_ALREADY_CANCELLED',

  // Internal and required infrastructure
  'REGISTRATION_UNAVAILABLE',
  'SERVICE_UNAVAILABLE',
  'INTERNAL_ERROR',
] as const;

export type PublicErrorCode = (typeof PUBLIC_ERROR_CODES)[number];

export const VALIDATION_VIOLATION_CODES = [
  'REQUIRED',
  'INVALID_TYPE',
  'INVALID_EMAIL',
  'INVALID_UUID',
  'INVALID_LENGTH',
  'VALUE_TOO_LONG',
  'WEAK_PASSWORD',
  'UNKNOWN_FIELD',
] as const;

export type ValidationViolationCode =
  (typeof VALIDATION_VIOLATION_CODES)[number];
